import { Room, TimetableEntry, StatusHistoryItem, NotificationItem, UserProfile } from './types';
import { MOCK_ROOMS } from '@/mock-data/rooms';
import { MOCK_STATUS_HISTORY } from '@/mock-data/statusHistory';
import { MOCK_NOTIFICATIONS } from '@/mock-data/notifications';
import { MOCK_USERS } from '@/mock-data/users';

export const INITIAL_ROOMS: Room[] = MOCK_ROOMS;

export const HIT_TIMETABLE: TimetableEntry[] = [
  // --- MONDAY ---
  {
    id: 'TT-MON-1-G1',
    day: 'Mon',
    startTime: '9:00 AM',
    endTime: '11:00 AM',
    startHour: 9.0,
    endHour: 11.0,
    subjectCode: 'DSC2155',
    subjectName: 'Design Thinking and IDEA Lab',
    room: 'ICT B08',
    group: 'Group 1',
    faculty: 'Prof. (Dr.) Subhajit Datta',
    facultyInitials: 'SD',
    ta: 'Ms. Tithi Dutta (TD)',
    type: 'Lab',
  },
  {
    id: 'TT-MON-1-G2',
    day: 'Mon',
    startTime: '9:00 AM',
    endTime: '12:00 PM',
    startHour: 9.0,
    endHour: 12.0,
    subjectCode: 'DSC2151',
    subjectName: 'Python Programming Lab',
    room: 'CME604',
    group: 'Group 2',
    faculty: 'To Be Announced',
    facultyInitials: 'TBA',
    ta: 'Mr. Srijit Talukdar (ST)',
    type: 'Lab',
  },
  {
    id: 'TT-MON-2-G1',
    day: 'Mon',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    startHour: 11.0,
    endHour: 12.0,
    subjectCode: 'MENTORING',
    subjectName: 'Mentoring Session',
    room: 'CB501',
    group: 'Group 1',
    faculty: 'CSE(DS) Faculty Panel',
    facultyInitials: 'Dept',
    type: 'Mentoring',
  },
  {
    id: 'TT-MON-3',
    day: 'Mon',
    startTime: '12:00 PM',
    endTime: '1:00 PM',
    startHour: 12.0,
    endHour: 13.0,
    subjectCode: 'REMEDIAL',
    subjectName: 'Industry Interaction / Remedial Class',
    room: 'CB501',
    group: 'All',
    faculty: 'Industry & Dept Faculty',
    facultyInitials: 'CB501',
    type: 'Remedial',
  },
  {
    id: 'TT-MON-BREAK',
    day: 'Mon',
    startTime: '1:00 PM',
    endTime: '2:00 PM',
    startHour: 13.0,
    endHour: 14.0,
    subjectCode: 'BREAK',
    subjectName: 'Recess / Lunch Break',
    room: 'Campus',
    group: 'All',
    faculty: '-',
    type: 'Break',
  },
  {
    id: 'TT-MON-4',
    day: 'Mon',
    startTime: '2:00 PM',
    endTime: '3:00 PM',
    startHour: 14.0,
    endHour: 15.0,
    subjectCode: 'CSE2101',
    subjectName: 'Data Structures and Algorithms',
    room: 'CB501',
    group: 'All',
    faculty: 'Prof. Deblina Chowdhury',
    facultyInitials: 'DLC',
    type: 'Lecture',
  },
  {
    id: 'TT-MON-5',
    day: 'Mon',
    startTime: '3:00 PM',
    endTime: '4:00 PM',
    startHour: 15.0,
    endHour: 16.0,
    subjectCode: 'EVS2016',
    subjectName: 'Environmental Sciences (Mandatory)',
    room: 'CB501',
    group: 'All',
    faculty: 'Prof. (Dr.) Piyali Paul',
    facultyInitials: 'PP',
    type: 'Lecture',
  },
  {
    id: 'TT-MON-6',
    day: 'Mon',
    startTime: '4:00 PM',
    endTime: '5:00 PM',
    startHour: 16.0,
    endHour: 17.0,
    subjectCode: 'ECE2002',
    subjectName: 'Digital Circuit Design',
    room: 'CB501',
    group: 'All',
    faculty: 'Prof. Ananya Chattopadhyay',
    facultyInitials: 'AC',
    type: 'Lecture',
  },

  // --- TUESDAY ---
  {
    id: 'TT-TUE-1',
    day: 'Tue',
    startTime: '9:00 AM',
    endTime: '10:00 AM',
    startHour: 9.0,
    endHour: 10.0,
    subjectCode: 'MTH2103',
    subjectName: 'Discrete Mathematics',
    room: 'CB501',
    group: 'All',
    faculty: 'Prof. (Dr.) Somjit Datta',
    facultyInitials: 'SD',
    type: 'Lecture',
  },
  {
    id: 'TT-TUE-2',
    day: 'Tue',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    startHour: 10.0,
    endHour: 11.0,
    subjectCode: 'CSE2101',
    subjectName: 'Data Structures and Algorithms',
    room: 'CB501',
    group: 'All',
    faculty: 'Prof. Deblina Chowdhury',
    facultyInitials: 'DLC',
    type: 'Lecture',
  },
  {
    id: 'TT-TUE-3',
    day: 'Tue',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    startHour: 11.0,
    endHour: 12.0,
    subjectCode: 'MTH2102',
    subjectName: 'Probability and Statistical Methods',
    room: 'CB501',
    group: 'All',
    faculty: 'Prof. (Dr.) Ritwick Banerjee',
    facultyInitials: 'RB',
    type: 'Lecture',
  },
  {
    id: 'TT-TUE-BREAK',
    day: 'Tue',
    startTime: '12:00 PM',
    endTime: '1:00 PM',
    startHour: 12.0,
    endHour: 13.0,
    subjectCode: 'BREAK',
    subjectName: 'Recess / Lunch Break',
    room: 'Campus',
    group: 'All',
    faculty: '-',
    type: 'Break',
  },
  {
    id: 'TT-TUE-4',
    day: 'Tue',
    startTime: '1:00 PM',
    endTime: '2:00 PM',
    startHour: 13.0,
    endHour: 14.0,
    subjectCode: 'CSE2101',
    subjectName: 'Data Structures and Algorithms',
    room: 'CB501',
    group: 'All',
    faculty: 'Prof. Deblina Chowdhury',
    facultyInitials: 'DLC',
    type: 'Lecture',
  },
  {
    id: 'TT-TUE-5-G1',
    day: 'Tue',
    startTime: '2:00 PM',
    endTime: '5:00 PM',
    startHour: 14.0,
    endHour: 17.0,
    subjectCode: 'DSC2151',
    subjectName: 'Python Programming Lab',
    room: 'CME604',
    group: 'Group 1',
    faculty: 'Prof. Arpita Talukdar',
    facultyInitials: 'AT',
    ta: 'Ms. Tithi Dutta (TD)',
    type: 'Lab',
  },
  {
    id: 'TT-TUE-5-G2',
    day: 'Tue',
    startTime: '2:00 PM',
    endTime: '4:00 PM',
    startHour: 14.0,
    endHour: 16.0,
    subjectCode: 'ECE2052',
    subjectName: 'Digital Circuit Design Laboratory',
    room: 'ICT403',
    group: 'Group 2',
    faculty: 'Prof. Ananya Chattopadhyay',
    facultyInitials: 'AC',
    ta: 'Mrs. Rubi Paul (RP) + Mr. Surojit Bera (SB)',
    type: 'Lab',
  },
  {
    id: 'TT-TUE-6-G2',
    day: 'Tue',
    startTime: '4:00 PM',
    endTime: '5:00 PM',
    startHour: 16.0,
    endHour: 17.0,
    subjectCode: 'MENTORING',
    subjectName: 'Mentoring Session',
    room: 'CB501',
    group: 'Group 2',
    faculty: 'CSE(DS) Faculty Panel',
    facultyInitials: 'Dept',
    type: 'Mentoring',
  },

  // --- WEDNESDAY ---
  {
    id: 'TT-WED-1-G1',
    day: 'Wed',
    startTime: '9:00 AM',
    endTime: '12:00 PM',
    startHour: 9.0,
    endHour: 12.0,
    subjectCode: 'CSE2151',
    subjectName: 'Data Structures and Algorithms Lab',
    room: 'ICT B08',
    group: 'Group 1',
    faculty: 'Prof. Deblina Chowdhury',
    facultyInitials: 'DLC',
    ta: 'Ms. Tithi Dutta (TD)',
    type: 'Lab',
  },
  {
    id: 'TT-WED-1-G2',
    day: 'Wed',
    startTime: '9:00 AM',
    endTime: '12:00 PM',
    startHour: 9.0,
    endHour: 12.0,
    subjectCode: 'CSE2151',
    subjectName: 'Data Structures and Algorithms Lab',
    room: 'CME604',
    group: 'Group 2',
    faculty: 'Prof. Arpita Talukdar',
    facultyInitials: 'AT',
    ta: 'Mr. Srijit Talukdar (ST)',
    type: 'Lab',
  },
  {
    id: 'TT-WED-BREAK',
    day: 'Wed',
    startTime: '12:00 PM',
    endTime: '1:00 PM',
    startHour: 12.0,
    endHour: 13.0,
    subjectCode: 'BREAK',
    subjectName: 'Recess / Lunch Break',
    room: 'Campus',
    group: 'All',
    faculty: '-',
    type: 'Break',
  },
  {
    id: 'TT-WED-2',
    day: 'Wed',
    startTime: '1:00 PM',
    endTime: '2:00 PM',
    startHour: 13.0,
    endHour: 14.0,
    subjectCode: 'DSC2101',
    subjectName: 'Python Programming',
    room: 'CB501',
    group: 'All',
    faculty: 'To Be Announced',
    facultyInitials: 'TBA',
    type: 'Lecture',
  },
  {
    id: 'TT-WED-3',
    day: 'Wed',
    startTime: '2:00 PM',
    endTime: '3:00 PM',
    startHour: 14.0,
    endHour: 15.0,
    subjectCode: 'MTH2103',
    subjectName: 'Discrete Mathematics',
    room: 'CB501',
    group: 'All',
    faculty: 'Prof. Venu Bihani',
    facultyInitials: 'VB',
    type: 'Lecture',
  },
  {
    id: 'TT-WED-4',
    day: 'Wed',
    startTime: '3:00 PM',
    endTime: '4:00 PM',
    startHour: 15.0,
    endHour: 16.0,
    subjectCode: 'ECE2002',
    subjectName: 'Digital Circuit Design',
    room: 'CB501',
    group: 'All',
    faculty: 'Prof. Ananya Chattopadhyay',
    facultyInitials: 'AC',
    type: 'Lecture',
  },
  {
    id: 'TT-WED-5',
    day: 'Wed',
    startTime: '4:00 PM',
    endTime: '5:00 PM',
    startHour: 16.0,
    endHour: 17.0,
    subjectCode: 'REMEDIAL',
    subjectName: 'Remedial Class',
    room: 'CB501',
    group: 'All',
    faculty: 'Department Faculty',
    facultyInitials: 'CB501',
    type: 'Remedial',
  },

  // --- THURSDAY ---
  {
    id: 'TT-THU-1',
    day: 'Thu',
    startTime: '9:00 AM',
    endTime: '10:00 AM',
    startHour: 9.0,
    endHour: 10.0,
    subjectCode: 'MTH2102',
    subjectName: 'Probability and Statistical Methods',
    room: 'CB601',
    group: 'All',
    faculty: 'Prof. (Dr.) Arpita Roy',
    facultyInitials: 'AR',
    type: 'Lecture',
  },
  {
    id: 'TT-THU-2',
    day: 'Thu',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    startHour: 10.0,
    endHour: 11.0,
    subjectCode: 'DSC2101',
    subjectName: 'Python Programming',
    room: 'CB601',
    group: 'All',
    faculty: 'To Be Announced',
    facultyInitials: 'TBA',
    type: 'Lecture',
  },
  {
    id: 'TT-THU-3',
    day: 'Thu',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    startHour: 11.0,
    endHour: 12.0,
    subjectCode: 'MTH2103',
    subjectName: 'Discrete Mathematics',
    room: 'CB601',
    group: 'All',
    faculty: 'Prof. (Dr.) Somjit Datta',
    facultyInitials: 'SD',
    type: 'Lecture',
  },
  {
    id: 'TT-THU-BREAK',
    day: 'Thu',
    startTime: '12:00 PM',
    endTime: '1:00 PM',
    startHour: 12.0,
    endHour: 13.0,
    subjectCode: 'BREAK',
    subjectName: 'Recess / Lunch Break',
    room: 'Campus',
    group: 'All',
    faculty: '-',
    type: 'Break',
  },
  {
    id: 'TT-THU-4',
    day: 'Thu',
    startTime: '1:00 PM',
    endTime: '2:00 PM',
    startHour: 13.0,
    endHour: 14.0,
    subjectCode: 'MTH2102',
    subjectName: 'Probability and Statistical Methods',
    room: 'CB501',
    group: 'All',
    faculty: 'Prof. (Dr.) Ritwick Banerjee',
    facultyInitials: 'RB',
    type: 'Lecture',
  },
  {
    id: 'TT-THU-5',
    day: 'Thu',
    startTime: '2:00 PM',
    endTime: '3:00 PM',
    startHour: 14.0,
    endHour: 15.0,
    subjectCode: 'CSE2101',
    subjectName: 'Data Structures and Algorithms',
    room: 'CB501',
    group: 'All',
    faculty: 'Prof. Deblina Chowdhury',
    facultyInitials: 'DLC',
    type: 'Lecture',
  },
  {
    id: 'TT-THU-6-G1',
    day: 'Thu',
    startTime: '3:00 PM',
    endTime: '5:00 PM',
    startHour: 15.0,
    endHour: 17.0,
    subjectCode: 'ECE2052',
    subjectName: 'Digital Circuit Design Laboratory',
    room: 'ICT403',
    group: 'Group 1',
    faculty: 'Prof. Ananya Chattopadhyay',
    facultyInitials: 'AC',
    ta: 'Mrs. Prativa Mondal (PM) + Mrs. Simantani Mondal (STM)',
    type: 'Lab',
  },
  {
    id: 'TT-THU-6-G2',
    day: 'Thu',
    startTime: '3:00 PM',
    endTime: '5:00 PM',
    startHour: 15.0,
    endHour: 17.0,
    subjectCode: 'DSC2155',
    subjectName: 'Design Thinking and IDEA Lab',
    room: 'ICT B08',
    group: 'Group 2',
    faculty: 'Prof. (Dr.) Subhajit Datta',
    facultyInitials: 'SD',
    ta: 'Ms. Tithi Dutta (TD)',
    type: 'Lab',
  },

  // --- FRIDAY ---
  {
    id: 'TT-FRI-1',
    day: 'Fri',
    startTime: '9:00 AM',
    endTime: '10:00 AM',
    startHour: 9.0,
    endHour: 10.0,
    subjectCode: 'DSC2101',
    subjectName: 'Python Programming',
    room: 'CB501',
    group: 'All',
    faculty: 'To Be Announced',
    facultyInitials: 'TBA',
    type: 'Lecture',
  },
  {
    id: 'TT-FRI-2',
    day: 'Fri',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    startHour: 10.0,
    endHour: 11.0,
    subjectCode: 'MTH2103',
    subjectName: 'Discrete Mathematics',
    room: 'CB501',
    group: 'All',
    faculty: 'Prof. Venu Bihani',
    facultyInitials: 'VB',
    type: 'Lecture',
  },
  {
    id: 'TT-FRI-3',
    day: 'Fri',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    startHour: 11.0,
    endHour: 12.0,
    subjectCode: 'ECE2002',
    subjectName: 'Digital Circuit Design',
    room: 'CB501',
    group: 'All',
    faculty: 'Prof. Ananya Chattopadhyay',
    facultyInitials: 'AC',
    type: 'Lecture',
  },
  {
    id: 'TT-FRI-BREAK',
    day: 'Fri',
    startTime: '12:00 PM',
    endTime: '1:00 PM',
    startHour: 12.0,
    endHour: 13.0,
    subjectCode: 'BREAK',
    subjectName: 'Recess / Lunch Break',
    room: 'Campus',
    group: 'All',
    faculty: '-',
    type: 'Break',
  },
  {
    id: 'TT-FRI-4',
    day: 'Fri',
    startTime: '1:00 PM',
    endTime: '2:00 PM',
    startHour: 13.0,
    endHour: 14.0,
    subjectCode: 'EVS2016',
    subjectName: 'Environmental Sciences (Mandatory)',
    room: 'CB501',
    group: 'All',
    faculty: 'Prof. (Dr.) Sangeeta Ghosh',
    facultyInitials: 'SG',
    type: 'Lecture',
  },
  {
    id: 'TT-FRI-5',
    day: 'Fri',
    startTime: '2:00 PM',
    endTime: '3:00 PM',
    startHour: 14.0,
    endHour: 15.0,
    subjectCode: 'MTH2102',
    subjectName: 'Probability and Statistical Methods',
    room: 'CB601',
    group: 'All',
    faculty: 'Prof. (Dr.) Arpita Roy',
    facultyInitials: 'AR',
    type: 'Lecture',
  },
  {
    id: 'TT-FRI-6',
    day: 'Fri',
    startTime: '3:00 PM',
    endTime: '5:00 PM',
    startHour: 15.0,
    endHour: 17.0,
    subjectCode: 'LIBRARY',
    subjectName: 'Library Session',
    room: 'LIBRARY',
    group: 'All',
    faculty: 'Central Library Staff',
    facultyInitials: 'LIB',
    type: 'Library',
  },
];

export const INITIAL_PROFILES: Record<string, UserProfile> = {
  student: {
    name: 'Nishant Ranjan',
    id: '2562014',
    rollNumber: '2562014',
    dept: 'Dept of Computer Science & Engineering (Data Science)',
    branch: 'CSE (Data Science)',
    year: '2nd Year',
    semester: '1st Semester',
    group: 'Group 1',
    roleLabel: 'Student Member',
    email: 'nishant.ranjan.ds29@heritageit.edu.in',
    avatar: 'NR',
    role: 'Student',
  },
  faculty: {
    name: 'Ritwick Banerjee',
    id: 'ritwick.banerjee@heritageit.edu',
    dept: 'Dept of Computer Science & Engineering',
    roleLabel: 'Faculty Member',
    email: 'ritwick.banerjee@heritageit.edu',
    avatar: 'RB',
    role: 'Faculty',
  },
  admin: {
    name: 'Subhajit Datta',
    id: 'subhajit.datta@heritageit.edu',
    dept: 'Campus Operations & Space Planning',
    roleLabel: 'Facility Administrator',
    email: 'subhajit.datta@heritageit.edu',
    avatar: 'SD',
    role: 'Admin',
  },
};

export const INITIAL_HISTORY: StatusHistoryItem[] = MOCK_STATUS_HISTORY as unknown as StatusHistoryItem[];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = MOCK_NOTIFICATIONS as unknown as NotificationItem[];

