import { Room, TimetableEntry, StatusHistoryItem, NotificationItem, UserProfile } from './types';
import { MOCK_ROOMS } from '@/mock-data/rooms';
import { MOCK_STATUS_HISTORY } from '@/mock-data/statusHistory';
import { MOCK_NOTIFICATIONS } from '@/mock-data/notifications';
import { MOCK_USERS } from '@/mock-data/users';

export const INITIAL_ROOMS: Room[] = MOCK_ROOMS;

export const HIT_TIMETABLE: TimetableEntry[] = [
  // Monday
  {
    id: 'TT-MON-1',
    day: 'Mon',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    startHour: 10.0,
    endHour: 11.0,
    subjectCode: 'CSEN2101',
    subjectName: 'Data Structures & Algorithms',
    room: 'CME604',
    group: 'All',
    faculty: 'Prof. S. Das',
  },
  {
    id: 'TT-MON-2',
    day: 'Mon',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    startHour: 11.0,
    endHour: 12.0,
    subjectCode: 'CSEN2102',
    subjectName: 'Computer Organization & Architecture',
    room: 'CB501',
    group: 'All',
    faculty: 'Prof. R. Banerjee',
  },
  {
    id: 'TT-MON-3-G1',
    day: 'Mon',
    startTime: '02:00 PM',
    endTime: '04:00 PM',
    startHour: 14.0,
    endHour: 16.0,
    subjectCode: 'CSEN2151',
    subjectName: 'Programming Practice (Practical Session)',
    room: 'ICT B08',
    group: 'Group 1',
    faculty: 'Prof. M. Ghosh',
  },
  {
    id: 'TT-MON-3-G2',
    day: 'Mon',
    startTime: '02:00 PM',
    endTime: '04:00 PM',
    startHour: 14.0,
    endHour: 16.0,
    subjectCode: 'CSEN2151',
    subjectName: 'Programming Practice (Practical Session)',
    room: 'ICT403',
    group: 'Group 2',
    faculty: 'Prof. T. Sen',
  },

  // Tuesday
  {
    id: 'TT-TUE-1',
    day: 'Tue',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    startHour: 10.0,
    endHour: 11.0,
    subjectCode: 'MATH2101',
    subjectName: 'Discrete Mathematics',
    room: 'CME-104',
    group: 'All',
    faculty: 'Prof. K. Paul',
  },
  {
    id: 'TT-TUE-2',
    day: 'Tue',
    startTime: '11:30 AM',
    endTime: '01:00 PM',
    startHour: 11.5,
    endHour: 13.0,
    subjectCode: 'CSEN2101',
    subjectName: 'Data Structures Tutorial',
    room: 'CME-101',
    group: 'All',
    faculty: 'Prof. S. Das',
  },
  {
    id: 'TT-TUE-3-G1',
    day: 'Tue',
    startTime: '02:00 PM',
    endTime: '04:00 PM',
    startHour: 14.0,
    endHour: 16.0,
    subjectCode: 'CSEN2152',
    subjectName: 'Data Structures Practice Session',
    room: 'ICT403',
    group: 'Group 1',
    faculty: 'Prof. S. Das',
  },
  {
    id: 'TT-TUE-3-G2',
    day: 'Tue',
    startTime: '02:00 PM',
    endTime: '04:00 PM',
    startHour: 14.0,
    endHour: 16.0,
    subjectCode: 'CSEN2152',
    subjectName: 'Data Structures Practice Session',
    room: 'ICT B08',
    group: 'Group 2',
    faculty: 'Prof. M. Ghosh',
  },

  // Wednesday
  {
    id: 'TT-WED-1',
    day: 'Wed',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    startHour: 10.0,
    endHour: 11.0,
    subjectCode: 'CSEN2103',
    subjectName: 'Object Oriented Programming',
    room: 'CME-104',
    group: 'All',
    faculty: 'Prof. A. Mukherjee',
  },
  {
    id: 'TT-WED-2',
    day: 'Wed',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    startHour: 11.0,
    endHour: 12.0,
    subjectCode: 'CSEN2102',
    subjectName: 'Computer Organization & Architecture',
    room: 'CB501',
    group: 'All',
    faculty: 'Prof. R. Banerjee',
  },
  {
    id: 'TT-WED-3',
    day: 'Wed',
    startTime: '01:30 PM',
    endTime: '03:00 PM',
    startHour: 13.5,
    endHour: 15.0,
    subjectCode: 'HMTS2101',
    subjectName: 'Academic Seminar / Communication',
    room: 'CME-103',
    group: 'All',
    faculty: 'Prof. P. Roy',
  },

  // Thursday
  {
    id: 'TT-THU-1',
    day: 'Thu',
    startTime: '09:30 AM',
    endTime: '11:00 AM',
    startHour: 9.5,
    endHour: 11.0,
    subjectCode: 'MATH2101',
    subjectName: 'Discrete Mathematics',
    room: 'CME-102',
    group: 'All',
    faculty: 'Prof. K. Paul',
  },
  {
    id: 'TT-THU-2',
    day: 'Thu',
    startTime: '11:30 AM',
    endTime: '01:00 PM',
    startHour: 11.5,
    endHour: 13.0,
    subjectCode: 'CSEN2101',
    subjectName: 'Data Structures & Algorithms',
    room: 'CME604',
    group: 'All',
    faculty: 'Prof. S. Das',
  },
  {
    id: 'TT-THU-3',
    day: 'Thu',
    startTime: '02:00 PM',
    endTime: '03:30 PM',
    startHour: 14.0,
    endHour: 15.5,
    subjectCode: 'SEMN2101',
    subjectName: 'Departmental Seminar Session',
    room: 'CME-103',
    group: 'All',
    faculty: 'Dept Faculty Panel',
  },

  // Friday
  {
    id: 'TT-FRI-1',
    day: 'Fri',
    startTime: '10:00 AM',
    endTime: '11:30 AM',
    startHour: 10.0,
    endHour: 11.5,
    subjectCode: 'CSEN2103',
    subjectName: 'OOP with Java',
    room: 'CME-104',
    group: 'All',
    faculty: 'Prof. A. Mukherjee',
  },
  {
    id: 'TT-FRI-2',
    day: 'Fri',
    startTime: '11:30 AM',
    endTime: '01:00 PM',
    startHour: 11.5,
    endHour: 13.0,
    subjectCode: 'HMTS2101',
    subjectName: 'Professional Communication',
    room: 'CB-102',
    group: 'All',
    faculty: 'Prof. P. Roy',
  },
  {
    id: 'TT-FRI-3-G1',
    day: 'Fri',
    startTime: '02:00 PM',
    endTime: '04:00 PM',
    startHour: 14.0,
    endHour: 16.0,
    subjectCode: 'CSEN2153',
    subjectName: 'Python for Data Science Session',
    room: 'ICT B08',
    group: 'Group 1',
    faculty: 'Prof. S. Datta',
  },
  {
    id: 'TT-FRI-3-G2',
    day: 'Fri',
    startTime: '02:00 PM',
    endTime: '04:00 PM',
    startHour: 14.0,
    endHour: 16.0,
    subjectCode: 'CSEN2153',
    subjectName: 'Python for Data Science Session',
    room: 'CB501',
    group: 'Group 2',
    faculty: 'Prof. A. Roy',
  },
];

export const INITIAL_PROFILES: Record<string, UserProfile> = {
  student: {
    name: 'Nishant Ranjan',
    id: '2562014',
    rollNumber: '2562014',
    dept: 'Dept of Computer Science & Engineering (Data Science)',
    branch: 'CSE (Data Science)',
    year: '2nd Year',
    semester: '1st Semester',
    group: 'Group 1',
    roleLabel: 'Student Member',
    email: 'nishant.ranjan.ds29@heritageit.edu.in',
    avatar: 'NR',
    role: 'Student',
  },
  faculty: {
    name: 'Ritwick Banerjee',
    id: 'ritwick.banerjee@heritageit.edu',
    dept: 'Dept of Computer Science & Engineering',
    roleLabel: 'Faculty Member',
    email: 'ritwick.banerjee@heritageit.edu',
    avatar: 'RB',
    role: 'Faculty',
  },
  admin: {
    name: 'Subhajit Datta',
    id: 'subhajit.datta@heritageit.edu',
    dept: 'Campus Operations & Space Planning',
    roleLabel: 'Facility Administrator',
    email: 'subhajit.datta@heritageit.edu',
    avatar: 'SD',
    role: 'Admin',
  },
};

export const INITIAL_HISTORY: StatusHistoryItem[] = MOCK_STATUS_HISTORY as unknown as StatusHistoryItem[];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = MOCK_NOTIFICATIONS as unknown as NotificationItem[];

